# -*- coding: utf-8 -*-
"""Travel_planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCQyry45GnQGD7un_dJEybLvVhP5E3hr
"""
import streamlit as st
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage

GOOGLE_API_KEY = "AIzaSyBMCc42a-cWcpnG1TfCC830kbHG20dAqpo"

Function to fetch AI-generated travel options
def get_travel_options(source, destination):
    try:
        system_prompt = SystemMessage(
            content="Provide travel options from {} to {}.".format(source, destination)
        )
        user_prompt = HumanMessage(content="I am traveling from {} to {}.".format(source, destination))
        
        llm = ChatGoogleGenerativeAI(model="gemini-1.5-pro", google_api_key=GOOGLE_API_KEY)
        response = llm.invoke([system_prompt, user_prompt])
        
        if response:
            return response.content
        else:
            return "No response from AI."
    
    except Exception as e:
        return "An error occurred: {}".format(str(e))

Streamlit UI
st.title("Travel Planner Assistant")
st.markdown("<h2>Your Personal Travel Guide</h2>", unsafe_allow_html=True)

Input fields for source and destination
source = st.text_input("Enter your source location:")
destination = st.text_input("Enter your destination location:")

Button to fetch travel options
if st.button("Get Travel Options"):
    if source and destination:
        options = get_travel_options(source, destination)
        st.write(options)
    else:
        st.error("Please enter both source and destination.")

